#!/usr/bin/env python3
import sys
from transfer.calcul_polynome import produit_polynome
from transfer.display_result import get_all_result

def get_args():
    list = []
    sous_list = []
    if len(sys.argv) < 3:
        exit(84)
    if (len(sys.argv) % 2 == 0):
        exit(84)
    for elt in sys.argv[1:]:
        try:
            sous_list = elt.split("*")
            for i in range(len(sous_list)):
                sous_list[i] = int(sous_list[i])
            list.append(sous_list)
        except ValueError:
            exit(84)
    return list

def main():
    list_args = get_args()
    numerateur = list_args[0]
    denominateur = list_args[1]

    # get the sum of all he numerators
    for i in range(2, len(list_args), 2):
        numerateur = produit_polynome(numerateur, list_args[i])

    # get the sum of all the denominators
    for i in range(3, len(list_args), 2):
        denominateur = produit_polynome(denominateur, list_args[i])

    try:
        get_all_result(numerateur, denominateur)
    except ZeroDivisionError:
        exit(84)
    exit(0)

if __name__ == "__main__":
    main()